version: '2'

services:
   nexus:
      image: "sonatype/nexus3"
      ports:
      - "8081:8081"
      volumes:
      - ./nexus-data:/nexus-data
   
   zookeeper1:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN
   
   zookeeper2:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN

   zookeeper3:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN

   kafka1:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN

   kafka2:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN
      
   avro1:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN
      
   avro2:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN
      
   kafka-misc:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN   
      
   reverse-proxy:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN   
      
   app-test:
      image: "andrefernandes/docker-systemd-sshd"
      tty: true
      volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      cap_add:
      - SYS_ADMIN   
      
   control:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2229:22"
      volumes:
      - /home/julien/Documents/ansible:/home/app-admin/ansible
      - ./ssh:/home/app-admin/ssh
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"
