version: '2'

services:
   nexus:
      image: "sonatype/nexus3"
      ports:
      - "8081:8081"
      volumes:
      - ./nexus-data:/opt/sonatype-work
   
   zookeeper1:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2222:22"   
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"
   
   zookeeper2:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2223:22"        
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"

   zookeeper3:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2224:22"        
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"

   kafka1:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2225:22"     
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"

   kafka2:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2226:22"    
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"
      
   avro1:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2227:22"    
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"
      
   avro2:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2228:22"
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"
      
   control:
      image: "jdeathe/centos-ssh"
      tty: true
      ports:
      - "2229:22"
      volumes:
      - /home/julien/Documents/ansible:/home/app-admin/ansible
      - ./ssh:/home/app-admin/ssh
      environment:
      - "SSH_SUDO=ALL=(ALL) NOPASSWD:ALL"
