- name: Check count of Consul hosts
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  fail: msg="The count of Consul hosts must be odd - found {{num_hosts | int}}"
  when: num_hosts | int % 2 == 0

- name: Install Consul
  yum: 
    name: "consul-server"
    state: latest
    
- name: Upload cluster settings file to Consul
  vars:
    server_list: "{{groups['consul']}}"
  template: 
    src: cluster.json.j2
    dest: /etc/consul.d/cluster.json
    mode: 0644
     
- name: Start Consul
  service:
    name: consul
    enabled: yes
    state: started
  when: auto_start_services
    
