- hosts: common
  roles:
  - { role: common }
  
- hosts: zookeeper
  roles:
  - { role: zookeeper }

- hosts: kafka
  roles:
  - { role: kafka }  

- hosts: kafka-rest
  roles:
  - { role: kafka-rest }   
  
- hosts: avro
  roles:
  - { role: avro }
  
- hosts: consul
  roles:
  - { role: consul }    

- hosts: api-gateway
  roles:
  - { role: api-gateway }   
