- hosts: common
  roles:
  - { role: common }
  
- hosts: zookeeper
  roles:
  - { role: zookeeper }

- hosts: kafka
  roles:
  - { role: kafka }  
  
- hosts: avro
  roles:
  - { role: avro }
  
- hosts: consul
  roles:
  - { role: consul }    
