- name: Check count of Zookeeper hosts
  vars:
    num_hosts: "{{ groups['zookeeper'] | length }}"
  fail: 
    msg: "The count of Zookeeper hosts must be odd - found {{num_hosts | int}}"
  when: num_hosts | int % 2 == 0

- name: Install Zookeeper
  yum: 
    name: "confluent-{{confluent_version}}-zookeeper-{{ gojulrpm_version }}"
    state: present
    
- name: Create data directory for Zookeeper
  file:
    path: "{{data_dir}}"
    state: directory
    owner: cp-kafka
    group: confluent
    recurse: yes
    
- name: Upload settings file to Zookeeper
  vars:
    server_list: "{{groups['zookeeper']}}"
  template: 
    src: zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.properties
    
- name: Assign ID to each Zookeeper instance
  shell: "echo {{groups.zookeeper.index(inventory_hostname) + 1}} > {{data_dir}}/myid"
  
- name: Start Zookeeper
  service:
    name: confluent-zookeeper
    enabled: yes
    state: started
  when: auto_start_services
    
