- name: Check count of Consul hosts
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  fail: 
    msg: "The count of Consul hosts must be odd - found {{num_hosts | int}}"
  when: num_hosts | int % 2 == 0

- name: Remove Consul Standalone
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum: 
    name: "consul-standalone"
    state: absent
  when: num_hosts | int > 1

- name: Remove Consul Server
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum: 
    name: "consul-server"
    state: absent
  when: num_hosts | int == 1

- name: Install Consul server
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum: 
    name: "consul-server-{{ gojulrpm_version }}"
    state: present
  when: num_hosts | int > 1

- name: Install Consul standalone
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum: 
    name: "consul-standalone-{{ gojulrpm_version }}"
    state: present
  when: num_hosts | int == 1
   
- name: Upload cluster settings file to Consul
  vars:
    server_list: "{{groups['consul']}}"
    num_hosts: "{{ groups['consul'] | length }}"
  template: 
    src: cluster.json.j2
    dest: /etc/consul.d/cluster.json
    mode: 0644
  when: num_hosts | int > 1
     
- name: Remove cluster settings for standalone Consul
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  file:
    path: /etc/consul.d/cluster.json
    state: absent
  when: num_hosts | int == 1

# Consul settings may have changed. In that case we
# must restart it.
- name: Start Consul
  service:
    name: consul
    enabled: yes
    state: restarted
  when: auto_start_services
    
