- name: Check count of Consul hosts
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  fail: 
    msg: "The count of Consul hosts must be greater than 0 - found {{num_hosts | int}}"
  when: num_hosts | int <= 0

- name: Remove Consul Client
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum:
    name: "consul-client"
    state: absent
  when: not use_consul_client

- name: Remove Consul Standalone
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum:
    name: "consul-standalone"
    state: absent
  when: use_consul_client

- name: Install Consul Client
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum:
    name: "consul-client-{{ gojulrpm_version }}"
    state: present
  when: use_consul_client

- name: Install Consul Standalone
  vars:
    num_hosts: "{{ groups['consul'] | length }}"
  yum:
    name: "consul-standalone-{{ gojulrpm_version }}"
    state: present
  when: not use_consul_client

- name: Install Consul Template
  yum: 
    name: "consul-template-{{ gojulrpm_version }}"
    state: present
    
- name: Upload consul client settings file to Consul
  vars:
    server_list: "{{groups['consul']}}"
  template: 
    src: cluster-client.json.j2
    dest: /etc/consul.d/cluster-client.json
    mode: 0644
  when: use_consul_client

- name: Remove consul client settings for standalone mode
  file:
    path: /etc/consul.d/cluster-client.json
    state: absent
  when: not use_consul_client

- name: Ensure directory consul-templates exist
  file: 
    path: "/etc/consul-templates"
    recurse: yes
    state: "directory"
    
- import_tasks: apache_specific.yml
  when: reverse_proxy == 'apache'

- import_tasks: nginx_specific.yml
  when: reverse_proxy == 'nginx'
  
# Is is safer to restart Consul client as its configuration
# may have changed. Thus it appears that Consul does NOT reconnect
# properly to a restarted cluster.
- name: Start Consul
  service:
    name: consul
    enabled: yes
    state: restarted
  when: auto_start_services
  
- name: Start Consul Template
  service:
    name: consul-template
    enabled: yes
    state: restarted
  when: auto_start_services
    
