- name: Configure YUM repos
  template:
    src: ../templates/gojul_microservices.repo.j2
    dest: /etc/yum.repos.d/gojul_microservices.repo
    
- name: Configure YUM to avoid RPMDb checksum errors
  yum: 
    name: "yum-plugin-ovl"
    state: "present"
